require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/favorite_workouts", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # FavoriteWorkout. As you add validations to FavoriteWorkout, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # FavoriteWorkoutsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      FavoriteWorkout.create! valid_attributes
      get favorite_workouts_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      favorite_workout = FavoriteWorkout.create! valid_attributes
      get favorite_workout_url(favorite_workout), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FavoriteWorkout" do
        expect {
          post favorite_workouts_url,
               params: { favorite_workout: valid_attributes }, headers: valid_headers, as: :json
        }.to change(FavoriteWorkout, :count).by(1)
      end

      it "renders a JSON response with the new favorite_workout" do
        post favorite_workouts_url,
             params: { favorite_workout: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FavoriteWorkout" do
        expect {
          post favorite_workouts_url,
               params: { favorite_workout: invalid_attributes }, as: :json
        }.to change(FavoriteWorkout, :count).by(0)
      end

      it "renders a JSON response with errors for the new favorite_workout" do
        post favorite_workouts_url,
             params: { favorite_workout: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested favorite_workout" do
        favorite_workout = FavoriteWorkout.create! valid_attributes
        patch favorite_workout_url(favorite_workout),
              params: { favorite_workout: new_attributes }, headers: valid_headers, as: :json
        favorite_workout.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the favorite_workout" do
        favorite_workout = FavoriteWorkout.create! valid_attributes
        patch favorite_workout_url(favorite_workout),
              params: { favorite_workout: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the favorite_workout" do
        favorite_workout = FavoriteWorkout.create! valid_attributes
        patch favorite_workout_url(favorite_workout),
              params: { favorite_workout: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested favorite_workout" do
      favorite_workout = FavoriteWorkout.create! valid_attributes
      expect {
        delete favorite_workout_url(favorite_workout), headers: valid_headers, as: :json
      }.to change(FavoriteWorkout, :count).by(-1)
    end
  end
end
